#this target will compile all the files
main:
	g++ main.cpp rtree.cpp leaf.cpp -o main -std=c++11

#all:	main.o rtree.o leaf.o
#	g++ -o all main.o rtree.o leaf.o

#main.o: main.cpp rtree.hpp
#	g++ -c main.cpp -std=c++11

#rtree.o: rtree.o rtree.hpp
#	g++ -c rtree.cpp -std=c++11

#leaf.o: leaf.o leaf.hpp
#	g++ -c leaf.cpp -std=c++11

clean:
	rm *o main